name: ItemReplenish
description: Replenishes broken tools and empty stacks with the items from your inventory.
author: JeffDziad
api-version: 1.19
version: 1.2
main: com.JeffDziad.ItemReplenish.ItemReplenish